site_name: "RAPTR API - St. Jude"
repo_url: "https://github.com/stjude/raptr"

site_description: "[HIGH LEVEL DISCRIPTION.]"
site_author: "St. Jude Cloud"
copyright: "© 2021 St. Jude Children's Research Hospital"

nav:
  - Home: "index.md"
  - API:
    - v1: 'api/v1/index.md'

theme: cosmo

plugins:
  - swagger-ui-tag
